### PR TITLE
Add docs for sync_ldap_users_and_groups command

### PR DESCRIPTION
**Pull request by gagantrivedi**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/deployment/locally-api#pre-commit) or manually with
      `npx pretty-quick` to check linting
- [x] I have filled in the "Changes" section below?

## Changes

Add documentation for `sync_ldap_users_and_groups` command

### CODE REVIEW

**Review by dabeeeenster — APPROVED** [review]

**Comment by matthewelwell** [comment]
@gagantrivedi @dabeeeenster these docs don't really provide any information as to how we expect people to run this. Given that LDAP is only available for enterprise self hosted customers we should probably be a bit more prescriptive? Maybe we should just have something in the helm templates for running a cron task? https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by dabeeeenster** [comment]
Ah yes good point - is there a URL endpoint that can be hit?

**Comment by matthewelwell** [comment]
No, at the moment, it's just a django management command. BUT, I think that's perhaps better. Looking at the docs I sent above, we should be able to add something like the following to our template. 

```yml
apiVersion: batch/v1
kind: CronJob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ldap-sync
            image: flagsmith:${{ api.version }}
            imagePullPolicy: IfNotPresent
            command:
            - python
            - manage.py
            - sync_ldap_users_and_groups
          restartPolicy: OnFailure
```

**Comment by dabeeeenster** [comment]
ah ok - can we get a new PR against the helm chart and then a new PR somewhere in the docs for this?

**Pull request merged**
